#!/usr/bin/env bash
#this script displays "Best School" 10 times using while loop

count=0

# Loop until counter reaches 10
while [ $count -lt 10 ]
do
    echo "Best School"
    # Increment counter
    ((count++))
done