#!usr/bin/env bash
#this script display "Best School" 10 times using the until loop

count=0

# Loop until counter reaches 10
until [ $count -ge 10 ]
do
    echo "Best School"
    # Increment counter
    ((count++))
done